# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0630713036dde9fc547372eb61002106fd4fdf581b57d7d3a45fa075a50191e786fe23e1c052619d3b2659c21cb44590b548b990a90896c83aba8f6c8ea1fbde

test:
  secret_key_base: ea31df523775aba7ba5f647130cfb5b3192b4104645972af0ac596a8423ba31121adde068cad9ad4fafe8c4c651028faa589ed25020fec0277ff6d669b4c6b82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
